config/routes.rb
Rails.application.routes.draw do
  get 'payments/success'
  devise_for :users, controllers: { registrations: "registrations" }
  get '/', to: "pages#index", as: "root"
  get "/", to: "pages#more"


  get "/", to: "listings#index", as: "listings"
  post "/", to: "listings#create"
  get "/new", to: "listings#new", as: "new_listing"
  get "/:id", to: "listings#show", as: "listing"
  put "/:id", to: "listings#update"
  patch "/:id", to: "listings#update"
  delete "/:id", to: "listings#destroy"
  get "/:id/edit", to: "listings#edit", as: "edit_listing"
  get "/manage", to: "listings#manage", as: "manage_listing"
  get "/:id/cart", to: "listings#cart", as: "cart"

  get "/payments/success", to: "payments#success"
  post "/:id", to: "payments#sold"


  get "/:path", to: "pages#not_found"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_nav.html.erb
<%#= -------------NavBar%>
<nav class ="navbar navbar-expand-md navbar-light bg-light sticky-top">
<div class = "container-fluid">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#burger">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class ="collapse navbar-collapse" id="burger">

        <ul class="navbar-nav mr-auto">

            <li class="nav-item active">
                <%= link_to "Home",root_path,class:"nav-link"%>
            </li>

            <li class="nav-item">
                <a class = "nav-link" href="#">Nike</a>
            </li>

            <li class="nav-item">
                <a class = "nav-link" href="#">Adidas</a>
            </li>

            <li class="nav-item">
                <a class = "nav-link" href="#">Jordan</a>
            </li>

            <li class="nav-item">
                <a class = "nav-link" href="#">Vans</a>
            </li>

            <li class="nav-item">
                <a class = "nav-link" href="#">Converse</a>
            </li>

            <li class="nav-item">
            <a class = "nav-link" href="#">New Balance</a>
            </li>

            <li class="nav-item">
            <a class = "nav-link" href="#">Sketchers</a>
            </li>
            
            <li class="nav-item">
            <a class = "nav-link" href="#">Under Armour</a>
            </li>
        </ul>

        <ul class="navbar-nav mr-auto" id="rightnav">

            <% if user_signed_in?%>

                <li class="nav-item">
                <%= search_form_for @q do |f| %>
                    <%= f.search_field :name_or_description_or_color_cont, class:"form-control",placeholder:"Search"  %>
                    <%#= f.submit %>
                <% end %>
                </li>

                <li class="nav-item m-auto">
                <div class="lead mr-3 ml-5 mt-1">
                hello, <%=current_user.name%>
                </div>
                </li>

                </li>
                <li class="nav-item">
                <%= link_to "Create Listing", new_listing_path , class:"btn btn-primary btn-space"%>
                </li>

                </li>
                <li class="nav-item">
                <%#= link_to "Mange Account", edit_listing_path , class:"btn btn-success btn-space"%>
                </li>

                <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, method: 'delete' , class:"btn btn-outline-secondary btn-space"%>
                </li>

                <li class="nav-item">
                <div class="m-auto">
                <%= link_to image_tag('cart.png', :size =>'30x25') %>
                </div>
                </li>

            <% else %>

            <li class="nav-item ">
            <%= search_form_for @q do |f| %>
                <%= f.search_field :name_or_description_or_color_cont, class:"form-control",placeholder:"Search" %>
                <%#= f.submit %>
            <% end %>
            </li>

            <li class="nav-item ">
            <div class="lead mr-3 ml-5 mt-1">
            hello, Guess
            </div>
            </li>

            <li class="nav-item">
            <%= link_to "Sign-in", new_user_session_path , class:"btn btn-primary btn-space" %>
            </li>

            <li class="nav-item">
            <%= link_to "Sign-up", new_user_registration_path , class:"btn btn-outline-secondary "%>
            </li>


            <% end %>
            
        </ul>

    </div>

</div>
</nav>

app/views/pages/index.html.erb
<%= render "nav"%>


<%#= -------------Slider%>
<div id="slides" class="carousel slide" data-ride="carousel">
<div class="carousel-inner">
<ul class="carousel-indicators">
    <li data-target="#slides" data-slide-to="0" class="active"></li>
    <li data-target="#slides" data-slide-to="1" ></li>
</ul>
    <div class="carousel-item active">
    <%= image_tag('cap3.jpg')%>

      <div class="carousel-caption">
      <%= image_tag('Zhus_logo_2_low.png', class:"caro")%>
      </div>

    </div>
    <div class="carousel-item">
    <%= image_tag('background2.jpg')%>
    <div class="carousel-caption">
    <%#= image_tag('Zhus_logo_2.png', class:"caro")%>
    </div>
</div>
</div>

<%#= -------------jumbotron%>

<div class="container-fluid">
<div class="row jumbotron">
    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9 col-xl-10">
    <h1 class="display-4">About Zhus</h1>
    <p class="lead"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam nec mauris arcu. Curabitur ac nisi vitae enim ultricies tincidunt gravida non ligula. Aenean consectetur odio vitae libero egestas facilisis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque elementum elit id elementum sagittis. Donec malesuada lorem et faucibus facilisis.
    </p>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-9 col-xl-4">
    <a href="#"><button type="button" class="btn btn-outline-primary btn-lg">More</button></a>
    </div>
</div>
</div>

<%#= -------------welcomesection%>
<div class="container-fluid padding">
<div class="row welcome text-center">
    <div class="col-12">
        <h1 class="display-5 lead"> Home Gallery</h1>
    </div>
    <hr>
    <div class="col-12">
    <p class="lead"></p>
    </div>
</div>
</div> 

<%#= -------------listingsection%>

<div class="container">

      <div class="row text-center">
        <% @listings.each do |listing| %>
            <div class="col-xs-12 col-md-4 col-lg-4 mt-5 mb-5 d-flex align-items-stretch">
                <div class="card" style="width: 18rem;">
                <%= image_tag (listing.picture), class:"card-img-top p-3" if listing.picture.attached?%>
                    <div class="card-body">
                    <h2 class="card-title"><%= listing.name.upcase %></h2>
                    <p class="card-text ">AUD: $<%= listing.price %></p>
                    <%= link_to "more",listing_path(listing.id), class:"btn btn-primary"%>
                    </div>
                </div>
            </div>
        <% end %>
      </div>
      

</div>

<%#= -------------background-------------%>

<figure>
<div class="fixed-wrap mb-5">dsadasd
      <div id="fixed">
      </div>
</div>
</figure>

<%#= -------------Featured Categories-------------%>

<div class="container-fluid gallery padding jumbotron">
<div class="row welcome text-center">
        <div class="col-12">
            <h1 class="lead display-5">Featured Gallery</h1>
        </div>
        <hr>

        <div class="container padding mt-5 mb-5 ">
        <div class="row row-cols-1 row-cols-md-3">

        <div class="col mb-4">
          <div class="card">
          <%=image_tag 'c1.jpg',class:"card-img-top"%>
            <div class="card-body">
              <h5 class="card-title">Casual</h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
          </div>
        </div>

        <div class="col mb-4">
          <div class="card">
          <%=image_tag 'c4.jpg',class:"card-img-top"%>
            <div class="card-body">
              <h5 class="card-title">Basketball</h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
          </div>
        </div>
  
        <div class="col mb-4">
          <div class="card">
          <%=image_tag 'c5.jpg',class:"card-img-top"%>
            <div class="card-body">
              <h5 class="card-title">Running</h5>
              <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
            </div>
          </div>
        </div>

</div>
</div>

</div>
</div>



<%#= -------------Philosphy------------%>


<%#= -------------media------------%>
<div class ="container-fluid padding">
<div class ="row text-center padding">

        <div class="col-12">
        <h2>Follow us</h2>
        </div>
        <div class="col-12 social padding">
        <a href=""><i class="fab fa-facebook"></i></a>
        <a href=""><i class="fab fa-youtube"></i></a>
        <a href=""><i class="fab fa-instagram"></i></a>
        <a href=""><i class="fab fa-twitter"></i></a>
        </div>

</div>
</div>

<%#= -------------footer------------%>
<div class="container-fluid footer padding mt-5">
<div class="row text-center">

        <div class="col-md-4">
        <h4>Legal</h4><br>
        <p>Tips & help</p>
        <p>About Zhus</p>
        <p>Help</p>
        <p>Contact Us</p>
        <p>Zhuz Classifieds</p>
        <p>StubHub</p>
        <p>Register</p>
        </div>

        
        <div class="col-md-4">
        <h4>Top Categories</h4><br>
        <p>Tips & help</p>
        <p>Casual</p>
        <p>Basketball</p>
        <p>Running</p>
        <p>Formal</p>
        <p>Skate & Canvas</p>
        <p>Other</p>
        </div>

        
        <div class="col-md-4">
        <h4>Zhus Favorites</h4><br>
        <p>Nike</p>
        <p>Adidas</p>
        <p>Converse</p>
        <p>Jordan</p>
        <p>Vans</p>
        <p>New Balance</p>
        <p>Under Armour</p>
        </div>
        <div class="col-12">
        <hr class="light">
        <h5>&copy; Zhus.com</h5>
        </div>

</div>
</div>

app/views/pages/more.html.erb
<%#= -------------NavBar%>
<nav class ="navbar navbar-expand-md navbar-light bg-light sticky-top">
<div class = "container-fluid">
    <%#= <a class="navbar-brand href=""> <%= image_tag('Zhus_logo.png', :size => '160x120')%> </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponive">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class ="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class = "nav-link" href="#">Home</a>
            </li>
            <li class="nav-item">
                <a class = "nav-link" href="#">Nike</a>
            </li>
            <li class="nav-item">
                <a class = "nav-link" href="#">Adidas</a>
            </li>
            <li class="nav-item">
                <a class = "nav-link" href="#">Jordan</a>
            </li>
            <li class="nav-item">
                <a class = "nav-link" href="#">Vans</a>
            </li>
            <li class="nav-item">
                <a class = "nav-link" href="#">Converse</a>
            </li>
            <li class="nav-item">
            <a class = "nav-link" href="#">New Balance</a>
            </li>
            <li class="nav-item">
            <a class = "nav-link" href="#">Sketchers</a>
            </li>
            <li class="nav-item">
            <a class = "nav-link" href="#">Under Armour</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            
            <li class="nav-item">
            <a class = "nav-link" href="#">Sign-in</a>
            </li>
            <li class="nav-item">
            <a class = "nav-link" href="#">Sign-up</a>
            </li>
            <%= image_tag('cart.png', :size =>'30x25')%>
        </ul>

    </div>

</div>
</nav>
<%#= -------------Slider%>
<div id="slides" class="carousel slide" data-ride="carousel">
<div class="carousel-inner">
<ul class="carousel-indicators">
    <li data-target="#slides" data-slide-to="0" class="active"></li>
    <li data-target="#slides" data-slide-to="1" ></li>
</ul>
    <div class="carousel-item active">
    <%= image_tag('background1.jpg')%>
    </div>
    <div class="carousel-item">
    <%= image_tag('background2.jpg')%>
</div>
</div>

<%#= -------------jumbotron%>
<div class="container-fluid">
<div class="row jumbotron">
    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9 col-xl-10">
    <h1 class="display-4">About Zhus</h1>
    <p class="lead"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam aliquam odio vel ipsum sodales, eget pellentesque neque porttitor. Aliquam purus felis, auctor sed neque vel,
    </p>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-9 col-xl-4">
    <a href="#"><button type="button" class="btn btn-outline-primary btn-lg">More</button></a>
    </div>
</div>
</div>

<%#= -------------welcomesection%>
<div class="container-fluid padding">
<div class="row welcome text-center">
    <div class="col-12">
        <h1 class="display-4"> Home Gallery</h1>
    </div>
    <hr>
    <div class="col-12">
    <p class="lead"></p>
    </div>
</div>
</div> 

<%#= -------------listingsection%>

app/views/pages/page_not_found.html.erb
<h1>Pages#page_not_found</h1>
<p>Find me in app/views/pages/page_not_found.html.erb</p>